# Generated by Django 6.0.3 on 2026-03-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('required_documents', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('crop', 'Crop'), ('subsidy', 'Subsidy'), ('equipment', 'Equipment'), ('irrigation', 'Irrigation'), ('insurance', 'Insurance')], default='subsidy', max_length=50)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('official_details_url', models.URLField()),
                ('apply_url', models.URLField()),
                ('icon_class', models.CharField(default='fas fa-leaf', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
