# Generated by Django 6.0 on 2026-03-21 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisanapp", "0002_govtscheme"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerLand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("land_name", models.CharField(max_length=150)),
                ("land_area", models.CharField(max_length=50)),
                (
                    "water_supply",
                    models.CharField(
                        choices=[
                            ("Borewell", "Borewell"),
                            ("Canal", "Canal"),
                            ("River", "River"),
                            ("Rain Water", "Rain Water"),
                            ("Drip Irrigation", "Drip Irrigation"),
                        ],
                        default="Borewell",
                        max_length=50,
                    ),
                ),
                (
                    "soil_method",
                    models.CharField(
                        choices=[
                            ("upload", "Upload Report"),
                            ("manual", "Manual Entry"),
                        ],
                        default="upload",
                        max_length=10,
                    ),
                ),
                (
                    "soil_report",
                    models.FileField(blank=True, null=True, upload_to="soil_reports/"),
                ),
                ("ph", models.CharField(blank=True, max_length=10, null=True)),
                ("ec", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "organic_carbon",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("nitrogen", models.CharField(blank=True, max_length=10, null=True)),
                ("phosphorus", models.CharField(blank=True, max_length=10, null=True)),
                ("potassium", models.CharField(blank=True, max_length=10, null=True)),
                ("sulphur", models.CharField(blank=True, max_length=10, null=True)),
                ("zinc", models.CharField(blank=True, max_length=10, null=True)),
                ("iron", models.CharField(blank=True, max_length=10, null=True)),
                ("manganese", models.CharField(blank=True, max_length=10, null=True)),
                ("copper", models.CharField(blank=True, max_length=10, null=True)),
                ("boron", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lands",
                        to="kisanapp.farmerregistration",
                    ),
                ),
            ],
        ),
    ]
