# Generated by Django 6.0 on 2026-03-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisanapp", "0003_farmerland"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Vegetable", "Vegetable"),
                            ("Fruit", "Fruit"),
                            ("Grain", "Grain"),
                            ("Pulse", "Pulse"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "kg"), ("quintal", "Quintal"), ("ton", "Ton")],
                        default="kg",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="crop_videos/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_listings",
                        to="kisanapp.farmerregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="crop_images/")),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="kisanapp.croplisting",
                    ),
                ),
            ],
        ),
    ]
