# Generated by Django 6.0 on 2026-03-23 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisanapp", "0004_croplisting_cropimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmingTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Tractor", "Tractor"),
                            ("Tractor Parts", "Tractor Parts"),
                            ("Irrigation Equipment", "Irrigation Equipment"),
                            ("Harvesting Tools", "Harvesting Tools"),
                            ("Sprayer", "Sprayer"),
                            ("Other Farming Equipment", "Other Farming Equipment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Good", "Good"),
                            ("Used", "Used"),
                            ("For Rent", "For Rent"),
                        ],
                        default="Good",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="tool_videos/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="kisanapp.farmerregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmingToolImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="tool_images/")),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="kisanapp.farmingtool",
                    ),
                ),
            ],
        ),
    ]
