# Generated by Django 6.0 on 2026-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisanapp", "0009_buyer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="district",
        ),
        migrations.RemoveField(
            model_name="buyer",
            name="state",
        ),
        migrations.RemoveField(
            model_name="buyer",
            name="taluka",
        ),
        migrations.RemoveField(
            model_name="buyer",
            name="village",
        ),
        migrations.AddField(
            model_name="buyer",
            name="locations",
            field=models.JSONField(
                default=list, help_text="List of {state, district, taluka} dicts"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="company",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
