# Generated by Django 6.0 on 2026-03-24 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisanapp", "0011_farmer_scheme_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_aadhar", models.BooleanField(default=False)),
                ("aadhar_number", models.CharField(blank=True, max_length=12)),
                ("has_pan", models.BooleanField(default=False)),
                ("pan_number", models.CharField(blank=True, max_length=10)),
                ("has_bank_account", models.BooleanField(default=False)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=20)),
                ("ifsc_code", models.CharField(blank=True, max_length=11)),
                ("has_land_record", models.BooleanField(default=False)),
                ("has_soil_health_card", models.BooleanField(default=False)),
                ("annual_income", models.CharField(blank=True, max_length=20)),
                ("has_income_cert", models.BooleanField(default=False)),
                (
                    "caste_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("General", "General"),
                            ("OBC", "OBC"),
                            ("SC", "SC"),
                            ("ST", "ST"),
                        ],
                        max_length=20,
                    ),
                ),
                ("has_caste_cert", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("has_photo", models.BooleanField(default=False)),
                (
                    "farmer_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="farmer_photos/"
                    ),
                ),
                ("has_ration_card", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_details",
                        to="kisanapp.farmerregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchemeNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("new_scheme", "New Scheme"),
                            ("status_update", "Application Status Update"),
                            ("reminder", "Apply Reminder"),
                        ],
                        default="new_scheme",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_notifications",
                        to="kisanapp.farmerschemeapplication",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_notifications",
                        to="kisanapp.farmerregistration",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_notifications",
                        to="kisanapp.govtscheme",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
