# Generated by Django 6.0 on 2026-03-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisanapp", "0012_farmerprofile_schemenotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerprofile",
            name="aadhar_doc",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_docs/aadhar/"
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="caste_cert_doc",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_docs/caste/"
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="caste_cert_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="income_cert_doc",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_docs/income/"
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="income_cert_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="land_record_doc",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_docs/land/"
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="land_record_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="pan_doc",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_docs/pan/"
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="ration_card_doc",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_docs/ration/"
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="ration_card_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="soil_health_card_doc",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_docs/soil/"
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="soil_health_card_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
