# Generated by Django 6.0 on 2026-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisanapp", "0014_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerregistration",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
