from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path("news/", views.agriculture_news, name="agriculture_news"),
    path("news/<int:article_id>/", views.news_details, name="news_details"),
    path('contact/', views.contact, name='contact'),
    path('govt_schemes/', views.govt_schemes, name='govt_schemes'),
    path('search/', views.search, name='search'),
    path("govt_scheme_detail/<int:pk>/", views.govt_scheme_detail, name="govt_scheme_detail"),
    path('market_price/', views.market_price, name='market_price'),
    path('register/', views.register, name='register'),
    path('add-land/', views.add_land, name='add_land'),
    path('edit-land/<int:land_id>/', views.edit_land, name='edit_land'),
    path('delete-land/<int:land_id>/', views.delete_land, name='delete_land'),
    path('soil-testing-form/', views.download_soil_form, name='download_soil_form'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('farming_guide/', views.farming_guide, name='farming_guide'),
    path('save-crop-plan/', views.save_crop_plan, name='save_crop_plan'),
    path('ai-assistant/', views.ai_assistant, name='ai_assistant'),
    path('ai-chat/', views.ai_chat, name='ai_chat'),
    path('notifications/', views.notifications, name='notifications'),
    path('notification-count/', views.notification_count, name='notification_count'),
    path('notifications-api/', views.notifications_api, name='notifications_api'),
    path('mark-activity/<int:activity_id>/', views.mark_activity_done, name='mark_activity_done'),
    path('send-otp/', views.send_otp, name='send_otp'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('send-login-otp/', views.send_login_otp, name='send_login_otp'),
    path('verify-login-otp/', views.verify_login_otp, name='verify_login_otp'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('crops_marketplace/', views.crops_marketplace, name='crops_marketplace'),
    path('farming_tools/', views.farming_tools, name='farming_tools'),
    path('buy-request/<int:crop_id>/', views.my_buy_requests, name='send_buy_request'),
    path('delete-crop/<int:crop_id>/', views.delete_crop_listing, name='delete_crop_listing'),
    # Buyer
    path('buyer/register/', views.buyer_register, name='buyer_register'),
    path('buyer/login/', views.buyer_login, name='buyer_login'),
    path('buyer/logout/', views.buyer_logout, name='buyer_logout'),
    path('buyer/profile/', views.buyer_profile, name='buyer_profile'),
    path('buyer/dashboard/', views.buyer_dashboard, name='buyer_dashboard'),
    path('buyer/send-otp/', views.send_buyer_otp, name='send_buyer_otp'),
    path('buyer/verify-otp/', views.verify_buyer_login_otp, name='verify_buyer_login_otp'),
    path('direct-buyers/', views.direct_buyers, name='direct_buyers'),
    # Location API
    path('api/states/', views.location_states, name='location_states'),
    path('api/districts/', views.location_districts, name='location_districts'),
    path('api/talukas/', views.location_talukas, name='location_talukas'),
    path('api/villages/', views.location_villages, name='location_villages'),
    # Farmer Profile & AI
    path('farmer-profile-form/', views.farmer_profile_form, name='farmer_profile_form'),
    path('soil-ai-suggest/', views.soil_ai_suggest, name='soil_ai_suggest'),
    # Scheme Apply
    path('scheme-apply/<int:scheme_id>/', views.scheme_apply, name='scheme_apply'),
    path('scheme-notifs-read/', views.mark_scheme_notifs_read, name='mark_scheme_notifs_read'),
    path('scheme-notif-count/', views.scheme_notif_count, name='scheme_notif_count'),
]